# Generated by Django 5.0.6 on 2024-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('Nombre_cancha', models.CharField(max_length=50)),
                ('id_cancha', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('disponible', models.BooleanField()),
                ('con_luz', models.BooleanField()),
                ('horario_reservado', models.BooleanField()),
                ('duracion_reserva', models.IntegerField()),
            ],
        ),
    ]
