# Generated by Django 5.0.6 on 2024-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCanchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='id_cancha',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
