# Generated by Django 5.0.6 on 2024-09-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCanchas', '0002_alter_cancha_id_cancha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Nombre_completo', models.CharField(max_length=50)),
                ('dni', models.BigIntegerField(primary_key=True, serialize=False)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
